import type { Metadata } from "next";
import "./globals.css";
import Aside from "@/components/Aside/Aside";
import Nav from "@/components/Nav/Nav";
import { localsNav, nav } from "@/data/fakeData";
import PageContainer from "@/components/PageContainer/PageContainer";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import Image from "next/image";
import InfoNumber from "@/components/InfoNumber/InfoNumber";
config.autoAddCss = false; /* eslint-disable import/first */


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex gap-6 mx-32 py-5 items-center">
          <div className="w-52 h-16 relative"><Image className="object-contain p-2" src='/brand.svg' alt="" fill /></div>
          <Header>
          <div className="bg-primary w-full rounded-md px-5 py-2 text-white flex gap-8 items-center justify-center">
            <InfoNumber icon="box-open" title="Transferências" number={20} variant="sm" />
            <InfoNumber icon="house" title="Cautelas" number={50} variant="sm" />
            <InfoNumber icon="calendar" title="Vencendo" number={200} variant="sm" />
            <InfoNumber icon="chart-line" title="Crescimento" number={120} variant="sm" />
            <InfoNumber icon="building" title="Itens sem local" number={450} variant="sm" />
          </div>
          <div className="flex gap-3 items-center">
            
            <div className="font-bold">Sgt Nome</div>
            <div className="w-14 h-14 relative border-2 rounded-full overflow-hidden">
              <Image className="object-contain" src='/materials/5.jpg' alt="" fill /></div>
          </div>
          </Header>
        </div>
        <div className="flex gap-6 mx-32">
        <Aside>
          <Nav items={nav} />
          <Nav items={localsNav} seeMoreUrl="/locais" variant="dark" size="sm" />
        </Aside>
        <div className="flex flex-col w-full">
        <PageContainer>
          {children}
        </PageContainer>
        <Footer>
            <div>St. B Norte QNB 1 - Taguatinga, Brasília - DF - CEP 72115-010</div>
            <div>CBMDF - Todos os direitos reservados</div>
        </Footer>
        </div>
      </div>
      </body>
    </html>
  );
}
